In [1]:
import flask
from flask import request, jsonify
import pandas as pd

app = flask.Flask(__name__)
app.config["DEBUG"] = True

In [3]:
df = pd.read_csv('E:/Research in Data/Assignments/Proposal/Olympics/data_2/api_dataset.csv')
df.head()

,Unnamed: 0,id,name,sex,age,height,weight,team,noc,games,year,season,city,sport,event,medal,region,notes
0,194731,98525,Maksim Sergeyevich Rakov,M,30.0,181.0,100.0,Kazakhstan,KAZ,2016 Summer,2016,Summer,Rio de Janeiro,Judo,Judo Men's Half-Heavyweight,NaN,Kazakhstan,NaN
1,162035,82008,"Alexandra Patricia ""Alex"" Morgan",F,27.0,173.0,62.0,United States,USA,2016 Summer,2016,Summer,Rio de Janeiro,Football,Football Women's Football,NaN,USA,NaN
2,117646,59981,Kim Hyeon-Seop,M,31.0,175.0,53.0,South Korea,KOR,2016 Summer,2016,Summer,Rio de Janeiro,Athletics,Athletics Men's 20 kilometres Walk,NaN,South Korea,NaN
3,117647,59981,Kim Hyeon-Seop,M,31.0,175.0,53.0,South Korea,KOR,2016 Summer,2016,Summer,Rio de Janeiro,Athletics,Athletics Men's 50 kilometres Walk,NaN,South Korea,NaN
4,38150,19756,Chang Hao,M,25.0,173.0,72.0,Chinese Taipei,TPE,2016 Summer,2016,Summer,Rio de Janeiro,Sailing,Sailing Men's Windsurfer,NaN,Taiwan,NaN

In [7]:
@app.route('/', methods=['GET'])
def home():return '''Olympics Data API'''